avaliacao/urls.py
from django.urls import path
from avaliacao.views import AvaliacaoCreateView
app_name = 'avaliacao'

urlpatterns = [

    path('addavaliacao', AvaliacaoCreateView.as_view(),name='add_avaliacao'),

]

core/urls.py
from escola.urls import path 

from core.views import index

app_name ='core'

urlpatterns = [
    path('', index, name='index'), #pagian inicial, view, name
]

escola/escola/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    
    #apps
    path('',include('users.urls')),
]

escola/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),

    #apps
    path('',include('users.urls')),
    path('',include('core.urls')),
    path('',include('avaliacao.urls'))
]

users/urls.py
from escola.urls import path
from users.views import UserLoginView, UserLogoutView, UserDetailView, AlunoDetailView, ProfessorDetailView

app_name = 'users'

urlpatterns = [
    path('login', UserLoginView.as_view(),name='login_users'),   
    path('logout', UserLogoutView.as_view(),name='logout_users'),
    path('users/<int:pk>/detalhes', UserDetailView.as_view(), name='detail_users'),
    path('users/<int:pk>/aluno', AlunoDetailView.as_view(), name='detalhes_aluno'),
    path('users/<int:pk>/professor', ProfessorDetailView.as_view(), name='detalhes_professor'),


]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}{%endblock title %}</title>
  <link href="https://fonts.googleapis.com/css?family=Berkshire+Swash&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
  <link rel="stylesheet" href="node_modules/bootstrap/compiler/stylenavs.css">

  {% block style %} {% endblock style %}

</head>

<body>

  <nav class="navbar navbar-dark bg-dark">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'core:index' %}">Olá, {{ request.user.nome }}
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Alterna navegação">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">

          {% if not request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login_users' %}">Login</a>
          </li>
          </form>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout_users' %}"> Logout </a>
          </li>
          {% endif %}
          </li>
          {% if request.user.is_professor %}
          <li><a class="nav-link" href="{% url 'users:detalhes_professor' request.user.id %}">SEUS DETALHES</a></li>
          <li><a class="nav-link" href="{% url 'avaliacao:add_avaliacao' %}">Dar nota</a></li>
          {% elif request.user.is_aluno %}
          <li><a class="nav-link" href="{% url 'users:detalhes_aluno' request.user.id %}">SEUS DETALHES</a></li>
          {% else %}
          {% endif %}




        </ul>
      </div>
    </nav>
  </nav>
  {% block body %}
  {% endblock body %}


  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"></script>
</body>

</html>l